spring:
  profiles:
    local:
      - "application-local"
    dev:
      - "application-dev"


  application:
    name: catastrophe-api

  data:
    jpa:
      repositories:
        bootstrap_mode: default # see https://github.com/spring-projects/spring-framework/issues/25111

  jpa:
    properties:
      hibernate:
        default_schema: public
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type.descriptor.sql.BasicBinder: TRACE

  flyway:
    baseline-on-migrate: true
    baseline-version: 0.1.0
    schemas: public
    table: flyway_schema_history

management:
  server:
    add-application-context-header: false
    port: 8081

server:
  port: 8080