#spring:
 # application:
  #  name: monkey
  #profiles:
  #  group:
   #   local-generic:
     #   - "pallas-local-logging"
    #  local:
      #  - "local"
      #dev:
      #  - "dev"

  #data:
   # jpa:
    #  repositories:
     #   bootstrap_mode: default # see https://github.com/spring-projects/spring-framework/issues/25111

  #flyway:
#    baseline-on-migrate: true
 #   baseline-version: 0.1.0
  #  schemas: public